remote_theme: pages-themes/architect@v0.2.0
title: Physical Notes De La Reed
description: Notes from Mr. Reed's 22-23 Physics Class
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
